# Generated by Django 4.0.4 on 2022-05-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='timeStamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
