# Generated by Django 4.0.4 on 2022-05-19 14:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=50)),
                ('yearReleased', models.CharField(max_length=4)),
                ('movieImg', models.ImageField(upload_to='images')),
            ],
        ),
    ]
